
-- First thing we want to do is create a warehouse
CREATE OR REPLACE WAREHOUSE data_api_wh WITH 
    WAREHOUSE_SIZE='X-SMALL'
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE;


-- Create the user and role in snowflake
USE ROLE ACCOUNTADMIN; 
CREATE ROLE DATA_API_ROLE; 

GRANT USAGE ON WAREHOUSE data_api_wh TO ROLE DATA_API_ROLE; 
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE DATA_API_ROLE; 
CREATE USER "DATA_API" PASSWORD = "password" DEFAULT_ROLE = DATA_API_ROLE DEFAULT_WAREHOUSE=data_api_wh DEFAULT_NAMESPACE=SNOWFLAKE_SAMPLE_DATA.TPCH_SF10 MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE DATA_API_ROLE TO USER DATA_API;