
-- First thing we want to do is create a warehouse
CREATE OR REPLACE WAREHOUSE data_api_wh WITH 
    WAREHOUSE_SIZE='X-SMALL'
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE;


-- Create the user and role in snowflake
USE ROLE ACCOUNTADMIN; 
CREATE ROLE DATA_API_ROLE; 

GRANT USAGE ON WAREHOUSE data_api_wh TO ROLE DATA_API_ROLE; 
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE DATA_API_ROLE; 
CREATE USER "DATA_API" PASSWORD = "password" DEFAULT_ROLE = DATA_API_ROLE DEFAULT_WAREHOUSE=data_api_wh DEFAULT_NAMESPACE=SNOWFLAKE_SAMPLE_DATA.TPCH_SF10 MUST_CHANGE_PASSWORD=FALSE;
 

 -- Give the user access to public key 

 ALTER USER "DATA_API" SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArrh/Lvdj1IOQhH3KWUn7
CHuIddhGtAJgU3/BpK0/kxh3n1wA7ZwxHJQVde3xANLHK6EOnQ13EVWiTe/X9CYj
1kLxbVedWL6aCa/Vhoyt7A9b1DfHPRQ1NGALsRJ0unBTSNt1D/MK+L8vFjKXTCLV
Iq9Ca5ALtZ731jzHtEuckS7rcalfK6vP8xNHA/qsGXsFVP5cBCBXLxEEzNrIKosW
PKyEuHqyngFD9DfHuRmJp04wB8uA1omB0mOGe4yjrKCjfLw3BbJ/0eLmBebhf00w
7auQefJmJAopzjyu6990UKGMIulj1GZ2LX8v42c4D0uqeRaLHHf4/om6eWqmFy1K
AQIDAQAB'; 